"""Document exporter utility for LegalLens using python-docx.

Exports summary, risks, and action plan into a clean, formatted Word (.docx) file.
"""

import io
from typing import Any, Dict, Optional
from docx import Document


def export_to_docx(
    summary_data: Optional[Dict[str, Any]] = None,
    risks_data: Optional[Dict[str, Any]] = None,
    action_data: Optional[Dict[str, Any]] = None,
    doc_name: str = "Document",
) -> io.BytesIO:
    """Generate a formatted Word (.docx) document summarizing analysis results.

    Args:
        summary_data: Dict from simplify_service (if available).
        risks_data: Dict from risk_service (if available).
        action_data: Dict from action_service (if available).
        doc_name: Name of the analyzed document.

    Returns:
        io.BytesIO stream containing the .docx file data.
    """
    doc = Document()

    # Title
    doc.add_heading(f"LegalLens Analysis Report: {doc_name}", level=0)

    # Disclaimer
    disclaimer = doc.add_paragraph(
        "DISCLAIMER: This report was generated by LegalLens for educational and informational "
        "purposes only. It does NOT constitute legal advice. Please consult a qualified attorney "
        "for professional legal counsel."
    )
    disclaimer.italic = True

    # 1. Summary Section
    if summary_data:
        doc.add_heading("1. Document Summary", level=1)
        doc.add_paragraph(f"Document Type: {summary_data.get('document_type', 'Not specified')}")
        doc.add_paragraph(summary_data.get("one_paragraph_summary", ""))

        key_points = summary_data.get("key_points", [])
        if key_points:
            doc.add_heading("Key Points", level=2)
            for kp in key_points:
                doc.add_paragraph(kp, style="List Bullet")

        glossary = summary_data.get("jargon_glossary", [])
        if glossary:
            doc.add_heading("Jargon Glossary", level=2)
            for item in glossary:
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(f"{item.get('term', '')}: ").bold = True
                p.add_run(item.get("simple_meaning", ""))

    # 2. Risks Section
    if risks_data:
        doc.add_heading("2. Risk & Clause Analysis", level=1)
        score = risks_data.get("overall_risk_score", "N/A")
        doc.add_paragraph(f"Overall Risk Score: {score} / 100")

        inconsistencies = risks_data.get("inconsistencies", [])
        if inconsistencies:
            doc.add_heading("Inconsistencies & Contradictions", level=2)
            for inc in inconsistencies:
                doc.add_paragraph(inc, style="List Bullet")

        clauses = risks_data.get("clauses", [])
        if clauses:
            doc.add_heading("Notable Clauses & Risks", level=2)
            for clause in clauses:
                title = clause.get("clause_title", "Clause")
                risk_lvl = clause.get("risk_level", "Low")
                category = clause.get("category", "Other")
                doc.add_heading(f"{title} [{risk_lvl} Risk - {category}]", level=3)

                quote = clause.get("exact_quote", "")
                if quote:
                    doc.add_paragraph(f"Quote: \"{quote}\"")
                doc.add_paragraph(f"Explanation: {clause.get('plain_explanation', '')}")
                doc.add_paragraph(f"Why it matters: {clause.get('why_it_matters', '')}")
                doc.add_paragraph(f"Suggested Question: {clause.get('suggested_question_to_ask', '')}")

    # 3. Action Plan Section
    if action_data:
        doc.add_heading("3. Action Plan", level=1)

        checklist = action_data.get("checklist_before_signing", [])
        if checklist:
            doc.add_heading("Checklist Before Signing", level=2)
            for item in checklist:
                doc.add_paragraph(f"[ ] {item}")

        obligations = action_data.get("obligations_and_deadlines", [])
        if obligations:
            doc.add_heading("Obligations & Deadlines", level=2)
            for ob in obligations:
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(f"What: {ob.get('what', '')} | Who: {ob.get('who', '')} | When: {ob.get('when', '')}")

        questions = action_data.get("questions_for_a_lawyer", [])
        if questions:
            doc.add_heading("Questions for a Lawyer", level=2)
            for i, q in enumerate(questions, start=1):
                doc.add_paragraph(f"{i}. {q}")

        next_steps = action_data.get("possible_next_steps", [])
        if next_steps:
            doc.add_heading("Possible Next Steps", level=2)
            for step in next_steps:
                doc.add_paragraph(step, style="List Bullet")

        documents = action_data.get("documents_to_gather", [])
        if documents:
            doc.add_heading("Documents to Gather", level=2)
            for d in documents:
                doc.add_paragraph(d, style="List Bullet")

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
